spring.datasource.url=jdbc:postgresql://postgres-common:5431/common-service
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=ramsharma
spring.datasource.password=995865
management.zipkin.tracing.endpoint=http://zipkin:9411
eureka.client.serviceUrl.defaultZone=http://eureka:password@discovery-server:8761/eureka